/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DSCUDARPC_H_RPCGEN
#define _DSCUDARPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef u_quad_t RCadr;

typedef u_quad_t RCstream;

typedef u_quad_t RCevent;

typedef u_quad_t RCipaddr;

typedef u_int RCsize;

typedef u_int RCerror;

typedef struct {
	u_int RCbuf_len;
	char *RCbuf_val;
} RCbuf;

typedef u_int RCchannelformat;

typedef u_long RCpid;

struct RCchanneldesc_t {
	RCchannelformat f;
	int w;
	int x;
	int y;
	int z;
};
typedef struct RCchanneldesc_t RCchanneldesc_t;

typedef RCchanneldesc_t RCchanneldesc;

struct RCtexture_t {
	int normalized;
	int filterMode;
	int addressMode[3];
	RCchannelformat f;
	int w;
	int x;
	int y;
	int z;
};
typedef struct RCtexture_t RCtexture_t;

typedef RCtexture_t RCtexture;

struct RCfuncattr_t {
	int binaryVersion;
	RCsize constSizeBytes;
	RCsize localSizeBytes;
	int maxThreadsPerBlock;
	int numRegs;
	int ptxVersion;
	RCsize sharedSizeBytes;
};
typedef struct RCfuncattr_t RCfuncattr_t;

typedef RCfuncattr_t RCfuncattr;

enum RCargType {
	dscudaArgTypeP = 0,
	dscudaArgTypeI = 1,
	dscudaArgTypeF = 2,
	dscudaArgTypeV = 3,
};
typedef enum RCargType RCargType;

struct RCargVal {
	RCargType type;
	union {
		RCadr address;
		u_int valuei;
		float valuef;
		char valuev[64];
	} RCargVal_u;
};
typedef struct RCargVal RCargVal;

struct RCarg {
	RCargVal val;
	u_int offset;
	u_int size;
};
typedef struct RCarg RCarg;

typedef struct {
	u_int RCargs_len;
	RCarg *RCargs_val;
} RCargs;

struct dscudaResult {
	RCerror err;
};
typedef struct dscudaResult dscudaResult;

struct dscudaThreadGetLimitResult {
	RCerror err;
	RCsize value;
};
typedef struct dscudaThreadGetLimitResult dscudaThreadGetLimitResult;

struct dscudaThreadGetCacheConfigResult {
	RCerror err;
	int cacheConfig;
};
typedef struct dscudaThreadGetCacheConfigResult dscudaThreadGetCacheConfigResult;

struct dscudaMallocResult {
	RCerror err;
	RCadr devAdr;
};
typedef struct dscudaMallocResult dscudaMallocResult;

struct dscudaHostAllocResult {
	RCerror err;
	RCadr pHost;
};
typedef struct dscudaHostAllocResult dscudaHostAllocResult;

struct dscudaMallocHostResult {
	RCerror err;
	RCadr ptr;
};
typedef struct dscudaMallocHostResult dscudaMallocHostResult;

struct dscudaMallocArrayResult {
	RCerror err;
	RCadr array;
};
typedef struct dscudaMallocArrayResult dscudaMallocArrayResult;

struct dscudaMallocPitchResult {
	RCerror err;
	RCadr devPtr;
	RCsize pitch;
};
typedef struct dscudaMallocPitchResult dscudaMallocPitchResult;

struct dscudaMemcpyD2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpyD2HResult dscudaMemcpyD2HResult;

struct dscudaMemcpyH2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpyH2HResult dscudaMemcpyH2HResult;

struct dscudaMemcpyToArrayD2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpyToArrayD2HResult dscudaMemcpyToArrayD2HResult;

struct dscudaMemcpyToArrayH2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpyToArrayH2HResult dscudaMemcpyToArrayH2HResult;

struct dscudaMemcpy2DToArrayD2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpy2DToArrayD2HResult dscudaMemcpy2DToArrayD2HResult;

struct dscudaMemcpy2DToArrayH2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpy2DToArrayH2HResult dscudaMemcpy2DToArrayH2HResult;

struct dscudaMemcpy2DD2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpy2DD2HResult dscudaMemcpy2DD2HResult;

struct dscudaMemcpy2DH2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpy2DH2HResult dscudaMemcpy2DH2HResult;

struct dscudaGetDeviceResult {
	RCerror err;
	int device;
};
typedef struct dscudaGetDeviceResult dscudaGetDeviceResult;

struct dscudaGetDeviceCountResult {
	RCerror err;
	int count;
};
typedef struct dscudaGetDeviceCountResult dscudaGetDeviceCountResult;

struct dscudaGetDevicePropertiesResult {
	RCerror err;
	RCbuf prop;
};
typedef struct dscudaGetDevicePropertiesResult dscudaGetDevicePropertiesResult;

struct dscudaDriverGetVersionResult {
	RCerror err;
	int ver;
};
typedef struct dscudaDriverGetVersionResult dscudaDriverGetVersionResult;

struct dscudaRuntimeGetVersionResult {
	RCerror err;
	int ver;
};
typedef struct dscudaRuntimeGetVersionResult dscudaRuntimeGetVersionResult;

struct dscudaGetErrorStringResult {
	char *errmsg;
};
typedef struct dscudaGetErrorStringResult dscudaGetErrorStringResult;

struct dscudaCreateChannelDescResult {
	int x;
	int y;
	int z;
	int w;
	RCchannelformat f;
};
typedef struct dscudaCreateChannelDescResult dscudaCreateChannelDescResult;

struct dscudaGetChannelDescResult {
	RCerror err;
	int x;
	int y;
	int z;
	int w;
	RCchannelformat f;
};
typedef struct dscudaGetChannelDescResult dscudaGetChannelDescResult;

struct dscudaChooseDeviceResult {
	RCerror err;
	int device;
};
typedef struct dscudaChooseDeviceResult dscudaChooseDeviceResult;

struct dscudaMemcpyAsyncD2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpyAsyncD2HResult dscudaMemcpyAsyncD2HResult;

struct dscudaMemcpyAsyncH2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpyAsyncH2HResult dscudaMemcpyAsyncH2HResult;

struct dscudaMemcpyFromSymbolD2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpyFromSymbolD2HResult dscudaMemcpyFromSymbolD2HResult;

struct dscudaMemcpyFromSymbolAsyncD2HResult {
	RCerror err;
	RCbuf buf;
};
typedef struct dscudaMemcpyFromSymbolAsyncD2HResult dscudaMemcpyFromSymbolAsyncD2HResult;

struct dscudaStreamCreateResult {
	RCerror err;
	RCadr stream;
};
typedef struct dscudaStreamCreateResult dscudaStreamCreateResult;

struct dscudaEventCreateResult {
	RCerror err;
	RCadr event;
};
typedef struct dscudaEventCreateResult dscudaEventCreateResult;

struct dscudaEventElapsedTimeResult {
	RCerror err;
	float ms;
};
typedef struct dscudaEventElapsedTimeResult dscudaEventElapsedTimeResult;

struct dscudaHostGetDevicePointerResult {
	RCerror err;
	RCadr pDevice;
};
typedef struct dscudaHostGetDevicePointerResult dscudaHostGetDevicePointerResult;

struct dscudaHostGetFlagsResult {
	RCerror err;
	u_int flags;
};
typedef struct dscudaHostGetFlagsResult dscudaHostGetFlagsResult;

struct dscudaLoadModuleResult {
	u_int id;
};
typedef struct dscudaLoadModuleResult dscudaLoadModuleResult;

struct dscudaFuncGetAttributesResult {
	RCerror err;
	RCfuncattr attr;
};
typedef struct dscudaFuncGetAttributesResult dscudaFuncGetAttributesResult;

struct dscudaBindTextureResult {
	RCerror err;
	RCsize offset;
};
typedef struct dscudaBindTextureResult dscudaBindTextureResult;

struct dscudaBindTexture2DResult {
	RCerror err;
	RCsize offset;
};
typedef struct dscudaBindTexture2DResult dscudaBindTexture2DResult;

struct dscufftResult {
	RCerror err;
};
typedef struct dscufftResult dscufftResult;

struct dscufftPlanResult {
	RCerror err;
	u_int plan;
};
typedef struct dscufftPlanResult dscufftPlanResult;

struct dscublasResult {
	RCerror err;
	u_int stat;
};
typedef struct dscublasResult dscublasResult;

struct dscublasCreateResult {
	RCerror err;
	u_int stat;
	RCadr handle;
};
typedef struct dscublasCreateResult dscublasCreateResult;

struct dscublasGetVectorResult {
	RCerror err;
	u_int stat;
	RCbuf y;
};
typedef struct dscublasGetVectorResult dscublasGetVectorResult;

struct RCdim3 {
	u_int x;
	u_int y;
	u_int z;
};
typedef struct RCdim3 RCdim3;

struct dscudathreadsetlimitid_1_argument {
	int limit;
	RCsize value;
};
typedef struct dscudathreadsetlimitid_1_argument dscudathreadsetlimitid_1_argument;

struct dscudastreamwaiteventid_1_argument {
	RCstream stream;
	RCevent event;
	u_int flags;
};
typedef struct dscudastreamwaiteventid_1_argument dscudastreamwaiteventid_1_argument;

struct dscudaeventelapsedtimeid_1_argument {
	RCevent start;
	RCevent end;
};
typedef struct dscudaeventelapsedtimeid_1_argument dscudaeventelapsedtimeid_1_argument;

struct dscudaeventrecordid_1_argument {
	RCevent event;
	RCstream stream;
};
typedef struct dscudaeventrecordid_1_argument dscudaeventrecordid_1_argument;

struct dscudalaunchkernelid_1_argument {
	int moduleid;
	int kid;
	char *kname;
	RCdim3 gdim;
	RCdim3 bdim;
	RCsize smemsize;
	RCstream stream;
	RCargs args;
};
typedef struct dscudalaunchkernelid_1_argument dscudalaunchkernelid_1_argument;

struct dscudaloadmoduleid_1_argument {
	RCipaddr ipaddr;
	RCpid pid;
	char *mname;
	char *image;
};
typedef struct dscudaloadmoduleid_1_argument dscudaloadmoduleid_1_argument;

struct dscudafuncgetattributesid_1_argument {
	int moduleid;
	char *kname;
};
typedef struct dscudafuncgetattributesid_1_argument dscudafuncgetattributesid_1_argument;

struct dscudamemcpyh2hid_1_argument {
	RCadr dst;
	RCbuf src;
	RCsize count;
};
typedef struct dscudamemcpyh2hid_1_argument dscudamemcpyh2hid_1_argument;

struct dscudamemcpyh2did_1_argument {
	RCadr dst;
	RCbuf src;
	RCsize count;
};
typedef struct dscudamemcpyh2did_1_argument dscudamemcpyh2did_1_argument;

struct dscudamemcpyd2hid_1_argument {
	RCadr src;
	RCsize count;
};
typedef struct dscudamemcpyd2hid_1_argument dscudamemcpyd2hid_1_argument;

struct dscudamemcpyd2did_1_argument {
	RCadr dst;
	RCadr src;
	RCsize count;
};
typedef struct dscudamemcpyd2did_1_argument dscudamemcpyd2did_1_argument;

struct dscudamemcpyasynch2hid_1_argument {
	RCadr dst;
	RCbuf src;
	RCsize count;
	RCstream stream;
};
typedef struct dscudamemcpyasynch2hid_1_argument dscudamemcpyasynch2hid_1_argument;

struct dscudamemcpyasynch2did_1_argument {
	RCadr dst;
	RCbuf src;
	RCsize count;
	RCstream stream;
};
typedef struct dscudamemcpyasynch2did_1_argument dscudamemcpyasynch2did_1_argument;

struct dscudamemcpyasyncd2hid_1_argument {
	RCadr src;
	RCsize count;
	RCstream stream;
};
typedef struct dscudamemcpyasyncd2hid_1_argument dscudamemcpyasyncd2hid_1_argument;

struct dscudamemcpyasyncd2did_1_argument {
	RCadr dst;
	RCadr src;
	RCsize count;
	RCstream stream;
};
typedef struct dscudamemcpyasyncd2did_1_argument dscudamemcpyasyncd2did_1_argument;

struct dscudamemcpytosymbolh2did_1_argument {
	int moduleid;
	char *symbol;
	RCbuf src;
	RCsize count;
	RCsize offset;
};
typedef struct dscudamemcpytosymbolh2did_1_argument dscudamemcpytosymbolh2did_1_argument;

struct dscudamemcpytosymbold2did_1_argument {
	int moduleid;
	char *symbol;
	RCadr src;
	RCsize count;
	RCsize offset;
};
typedef struct dscudamemcpytosymbold2did_1_argument dscudamemcpytosymbold2did_1_argument;

struct dscudamemcpyfromsymbold2hid_1_argument {
	int moduleid;
	char *symbol;
	RCsize count;
	RCsize offset;
};
typedef struct dscudamemcpyfromsymbold2hid_1_argument dscudamemcpyfromsymbold2hid_1_argument;

struct dscudamemcpyfromsymbold2did_1_argument {
	int moduleid;
	RCadr dst;
	char *symbol;
	RCsize count;
	RCsize offset;
};
typedef struct dscudamemcpyfromsymbold2did_1_argument dscudamemcpyfromsymbold2did_1_argument;

struct dscudamemsetid_1_argument {
	RCadr dst;
	int value;
	RCsize count;
};
typedef struct dscudamemsetid_1_argument dscudamemsetid_1_argument;

struct dscudahostallocid_1_argument {
	RCsize size;
	u_int flags;
};
typedef struct dscudahostallocid_1_argument dscudahostallocid_1_argument;

struct dscudahostgetdevicepointerid_1_argument {
	RCadr pHost;
	u_int flags;
};
typedef struct dscudahostgetdevicepointerid_1_argument dscudahostgetdevicepointerid_1_argument;

struct dscudamallocarrayid_1_argument {
	RCchanneldesc desc;
	RCsize width;
	RCsize height;
	u_int flags;
};
typedef struct dscudamallocarrayid_1_argument dscudamallocarrayid_1_argument;

struct dscudamemcpytoarrayh2hid_1_argument {
	RCadr dst;
	RCsize wOffset;
	RCsize hOffset;
	RCbuf src;
	RCsize count;
};
typedef struct dscudamemcpytoarrayh2hid_1_argument dscudamemcpytoarrayh2hid_1_argument;

struct dscudamemcpytoarrayh2did_1_argument {
	RCadr dst;
	RCsize wOffset;
	RCsize hOffset;
	RCbuf src;
	RCsize count;
};
typedef struct dscudamemcpytoarrayh2did_1_argument dscudamemcpytoarrayh2did_1_argument;

struct dscudamemcpytoarrayd2hid_1_argument {
	RCsize wOffset;
	RCsize hOffset;
	RCadr src;
	RCsize count;
};
typedef struct dscudamemcpytoarrayd2hid_1_argument dscudamemcpytoarrayd2hid_1_argument;

struct dscudamemcpytoarrayd2did_1_argument {
	RCadr dst;
	RCsize wOffset;
	RCsize hOffset;
	RCadr src;
	RCsize count;
};
typedef struct dscudamemcpytoarrayd2did_1_argument dscudamemcpytoarrayd2did_1_argument;

struct dscudamallocpitchid_1_argument {
	RCsize width;
	RCsize height;
};
typedef struct dscudamallocpitchid_1_argument dscudamallocpitchid_1_argument;

struct dscudamemcpy2dtoarrayh2hid_1_argument {
	RCadr dst;
	RCsize wOffset;
	RCsize hOffset;
	RCbuf src;
	RCsize spitch;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemcpy2dtoarrayh2hid_1_argument dscudamemcpy2dtoarrayh2hid_1_argument;

struct dscudamemcpy2dtoarrayh2did_1_argument {
	RCadr dst;
	RCsize wOffset;
	RCsize hOffset;
	RCbuf srcbuf;
	RCsize spitch;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemcpy2dtoarrayh2did_1_argument dscudamemcpy2dtoarrayh2did_1_argument;

struct dscudamemcpy2dtoarrayd2hid_1_argument {
	RCsize wOffset;
	RCsize hOffset;
	RCadr src;
	RCsize spitch;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemcpy2dtoarrayd2hid_1_argument dscudamemcpy2dtoarrayd2hid_1_argument;

struct dscudamemcpy2dtoarrayd2did_1_argument {
	RCadr dst;
	RCsize wOffset;
	RCsize hOffset;
	RCadr src;
	RCsize spitch;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemcpy2dtoarrayd2did_1_argument dscudamemcpy2dtoarrayd2did_1_argument;

struct dscudamemcpy2dh2hid_1_argument {
	RCadr dst;
	RCsize dpitch;
	RCbuf src;
	RCsize spitch;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemcpy2dh2hid_1_argument dscudamemcpy2dh2hid_1_argument;

struct dscudamemcpy2dh2did_1_argument {
	RCadr dst;
	RCsize dpitch;
	RCbuf src;
	RCsize spitch;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemcpy2dh2did_1_argument dscudamemcpy2dh2did_1_argument;

struct dscudamemcpy2dd2hid_1_argument {
	RCsize dpitch;
	RCadr src;
	RCsize spitch;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemcpy2dd2hid_1_argument dscudamemcpy2dd2hid_1_argument;

struct dscudamemcpy2dd2did_1_argument {
	RCadr dst;
	RCsize dpitch;
	RCadr src;
	RCsize spitch;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemcpy2dd2did_1_argument dscudamemcpy2dd2did_1_argument;

struct dscudamemset2did_1_argument {
	RCadr dst;
	RCsize pitch;
	int value;
	RCsize width;
	RCsize height;
};
typedef struct dscudamemset2did_1_argument dscudamemset2did_1_argument;

struct dscudamemcpytosymbolasynch2did_1_argument {
	int moduleid;
	char *symbol;
	RCbuf src;
	RCsize count;
	RCsize offset;
	RCstream stream;
};
typedef struct dscudamemcpytosymbolasynch2did_1_argument dscudamemcpytosymbolasynch2did_1_argument;

struct dscudamemcpytosymbolasyncd2did_1_argument {
	int moduleid;
	char *symbol;
	RCadr src;
	RCsize count;
	RCsize offset;
	RCstream stream;
};
typedef struct dscudamemcpytosymbolasyncd2did_1_argument dscudamemcpytosymbolasyncd2did_1_argument;

struct dscudamemcpyfromsymbolasyncd2hid_1_argument {
	int moduleid;
	char *symbol;
	RCsize count;
	RCsize offset;
	RCstream stream;
};
typedef struct dscudamemcpyfromsymbolasyncd2hid_1_argument dscudamemcpyfromsymbolasyncd2hid_1_argument;

struct dscudamemcpyfromsymbolasyncd2did_1_argument {
	int moduleid;
	RCadr dst;
	char *symbol;
	RCsize count;
	RCsize offset;
	RCstream stream;
};
typedef struct dscudamemcpyfromsymbolasyncd2did_1_argument dscudamemcpyfromsymbolasyncd2did_1_argument;

struct dscudacreatechanneldescid_1_argument {
	int x;
	int y;
	int z;
	int w;
	RCchannelformat f;
};
typedef struct dscudacreatechanneldescid_1_argument dscudacreatechanneldescid_1_argument;

struct dscudabindtextureid_1_argument {
	int moduleid;
	char *texname;
	RCadr devPtr;
	RCsize size;
	RCtexture texbuf;
};
typedef struct dscudabindtextureid_1_argument dscudabindtextureid_1_argument;

struct dscudabindtexture2did_1_argument {
	int moduleid;
	char *texname;
	RCadr devPtr;
	RCsize width;
	RCsize height;
	RCsize pitch;
	RCtexture texbuf;
};
typedef struct dscudabindtexture2did_1_argument dscudabindtexture2did_1_argument;

struct dscudabindtexturetoarrayid_1_argument {
	int moduleid;
	char *texname;
	RCadr array;
	RCtexture texbuf;
};
typedef struct dscudabindtexturetoarrayid_1_argument dscudabindtexturetoarrayid_1_argument;

struct dscufftplan3did_1_argument {
	int nx;
	int ny;
	int nz;
	u_int type;
};
typedef struct dscufftplan3did_1_argument dscufftplan3did_1_argument;

struct dscufftexecc2cid_1_argument {
	u_int plan;
	RCadr idata;
	RCadr odata;
	int direction;
};
typedef struct dscufftexecc2cid_1_argument dscufftexecc2cid_1_argument;

#define DSCUDA_PROG 60000
#define DSCUDA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define dscudaThreadExitId 100
extern  dscudaResult * dscudathreadexitid_1(CLIENT *);
extern  dscudaResult * dscudathreadexitid_1_svc(struct svc_req *);
#define dscudaThreadSynchronizeId 101
extern  dscudaResult * dscudathreadsynchronizeid_1(CLIENT *);
extern  dscudaResult * dscudathreadsynchronizeid_1_svc(struct svc_req *);
#define dscudaThreadSetLimitId 102
extern  dscudaResult * dscudathreadsetlimitid_1(int , RCsize , CLIENT *);
extern  dscudaResult * dscudathreadsetlimitid_1_svc(int , RCsize , struct svc_req *);
#define dscudaThreadGetLimitId 103
extern  dscudaThreadGetLimitResult * dscudathreadgetlimitid_1(int , CLIENT *);
extern  dscudaThreadGetLimitResult * dscudathreadgetlimitid_1_svc(int , struct svc_req *);
#define dscudaThreadSetCacheConfigId 104
extern  dscudaResult * dscudathreadsetcacheconfigid_1(int , CLIENT *);
extern  dscudaResult * dscudathreadsetcacheconfigid_1_svc(int , struct svc_req *);
#define dscudaThreadGetCacheConfigId 105
extern  dscudaThreadGetCacheConfigResult * dscudathreadgetcacheconfigid_1(CLIENT *);
extern  dscudaThreadGetCacheConfigResult * dscudathreadgetcacheconfigid_1_svc(struct svc_req *);
#define dscudaGetLastErrorId 200
extern  dscudaResult * dscudagetlasterrorid_1(CLIENT *);
extern  dscudaResult * dscudagetlasterrorid_1_svc(struct svc_req *);
#define dscudaPeekAtLastErrorId 201
extern  dscudaResult * dscudapeekatlasterrorid_1(CLIENT *);
extern  dscudaResult * dscudapeekatlasterrorid_1_svc(struct svc_req *);
#define dscudaGetErrorStringId 202
extern  dscudaGetErrorStringResult * dscudageterrorstringid_1(int , CLIENT *);
extern  dscudaGetErrorStringResult * dscudageterrorstringid_1_svc(int , struct svc_req *);
#define dscudaGetDeviceId 300
extern  dscudaGetDeviceResult * dscudagetdeviceid_1(CLIENT *);
extern  dscudaGetDeviceResult * dscudagetdeviceid_1_svc(struct svc_req *);
#define dscudaGetDeviceCountId 301
extern  dscudaGetDeviceCountResult * dscudagetdevicecountid_1(CLIENT *);
extern  dscudaGetDeviceCountResult * dscudagetdevicecountid_1_svc(struct svc_req *);
#define dscudaGetDevicePropertiesId 302
extern  dscudaGetDevicePropertiesResult * dscudagetdevicepropertiesid_1(int , CLIENT *);
extern  dscudaGetDevicePropertiesResult * dscudagetdevicepropertiesid_1_svc(int , struct svc_req *);
#define dscudaDriverGetVersionId 303
extern  dscudaDriverGetVersionResult * dscudadrivergetversionid_1(CLIENT *);
extern  dscudaDriverGetVersionResult * dscudadrivergetversionid_1_svc(struct svc_req *);
#define dscudaRuntimeGetVersionId 304
extern  dscudaRuntimeGetVersionResult * dscudaruntimegetversionid_1(CLIENT *);
extern  dscudaRuntimeGetVersionResult * dscudaruntimegetversionid_1_svc(struct svc_req *);
#define dscudaSetDeviceId 305
extern  dscudaResult * dscudasetdeviceid_1(int , CLIENT *);
extern  dscudaResult * dscudasetdeviceid_1_svc(int , struct svc_req *);
#define dscudaSetDeviceFlagsId 306
extern  dscudaResult * dscudasetdeviceflagsid_1(u_int , CLIENT *);
extern  dscudaResult * dscudasetdeviceflagsid_1_svc(u_int , struct svc_req *);
#define dscudaChooseDeviceId 307
extern  dscudaChooseDeviceResult * dscudachoosedeviceid_1(RCbuf , CLIENT *);
extern  dscudaChooseDeviceResult * dscudachoosedeviceid_1_svc(RCbuf , struct svc_req *);
#define dscudaDeviceSynchronize 308
extern  dscudaResult * dscudadevicesynchronize_1(CLIENT *);
extern  dscudaResult * dscudadevicesynchronize_1_svc(struct svc_req *);
#define dscudaDeviceReset 309
extern  dscudaResult * dscudadevicereset_1(CLIENT *);
extern  dscudaResult * dscudadevicereset_1_svc(struct svc_req *);
#define dscudaStreamCreateId 400
extern  dscudaStreamCreateResult * dscudastreamcreateid_1(CLIENT *);
extern  dscudaStreamCreateResult * dscudastreamcreateid_1_svc(struct svc_req *);
#define dscudaStreamDestroyId 401
extern  dscudaResult * dscudastreamdestroyid_1(RCstream , CLIENT *);
extern  dscudaResult * dscudastreamdestroyid_1_svc(RCstream , struct svc_req *);
#define dscudaStreamSynchronizeId 402
extern  dscudaResult * dscudastreamsynchronizeid_1(RCstream , CLIENT *);
extern  dscudaResult * dscudastreamsynchronizeid_1_svc(RCstream , struct svc_req *);
#define dscudaStreamQueryId 403
extern  dscudaResult * dscudastreamqueryid_1(RCstream , CLIENT *);
extern  dscudaResult * dscudastreamqueryid_1_svc(RCstream , struct svc_req *);
#define dscudaStreamWaitEventId 404
extern  dscudaResult * dscudastreamwaiteventid_1(RCstream , RCevent , u_int , CLIENT *);
extern  dscudaResult * dscudastreamwaiteventid_1_svc(RCstream , RCevent , u_int , struct svc_req *);
#define dscudaEventCreateId 500
extern  dscudaEventCreateResult * dscudaeventcreateid_1(CLIENT *);
extern  dscudaEventCreateResult * dscudaeventcreateid_1_svc(struct svc_req *);
#define dscudaEventCreateWithFlagsId 501
extern  dscudaEventCreateResult * dscudaeventcreatewithflagsid_1(u_int , CLIENT *);
extern  dscudaEventCreateResult * dscudaeventcreatewithflagsid_1_svc(u_int , struct svc_req *);
#define dscudaEventDestroyId 502
extern  dscudaResult * dscudaeventdestroyid_1(RCevent , CLIENT *);
extern  dscudaResult * dscudaeventdestroyid_1_svc(RCevent , struct svc_req *);
#define dscudaEventElapsedTimeId 503
extern  dscudaEventElapsedTimeResult * dscudaeventelapsedtimeid_1(RCevent , RCevent , CLIENT *);
extern  dscudaEventElapsedTimeResult * dscudaeventelapsedtimeid_1_svc(RCevent , RCevent , struct svc_req *);
#define dscudaEventRecordId 504
extern  dscudaResult * dscudaeventrecordid_1(RCevent , RCstream , CLIENT *);
extern  dscudaResult * dscudaeventrecordid_1_svc(RCevent , RCstream , struct svc_req *);
#define dscudaEventSynchronizeId 505
extern  dscudaResult * dscudaeventsynchronizeid_1(RCevent , CLIENT *);
extern  dscudaResult * dscudaeventsynchronizeid_1_svc(RCevent , struct svc_req *);
#define dscudaEventQueryId 506
extern  dscudaResult * dscudaeventqueryid_1(RCevent , CLIENT *);
extern  dscudaResult * dscudaeventqueryid_1_svc(RCevent , struct svc_req *);
#define dscudaLaunchKernelId 600
extern  void * dscudalaunchkernelid_1(int , int , char *, RCdim3 , RCdim3 , RCsize , RCstream , RCargs , CLIENT *);
extern  void * dscudalaunchkernelid_1_svc(int , int , char *, RCdim3 , RCdim3 , RCsize , RCstream , RCargs , struct svc_req *);
#define dscudaLoadModuleId 601
extern  dscudaLoadModuleResult * dscudaloadmoduleid_1(RCipaddr , RCpid , char *, char *, CLIENT *);
extern  dscudaLoadModuleResult * dscudaloadmoduleid_1_svc(RCipaddr , RCpid , char *, char *, struct svc_req *);
#define dscudaFuncGetAttributesId 602
extern  dscudaFuncGetAttributesResult * dscudafuncgetattributesid_1(int , char *, CLIENT *);
extern  dscudaFuncGetAttributesResult * dscudafuncgetattributesid_1_svc(int , char *, struct svc_req *);
#define dscudaMallocId 700
extern  dscudaMallocResult * dscudamallocid_1(RCsize , CLIENT *);
extern  dscudaMallocResult * dscudamallocid_1_svc(RCsize , struct svc_req *);
#define dscudaFreeId 701
extern  dscudaResult * dscudafreeid_1(RCadr , CLIENT *);
extern  dscudaResult * dscudafreeid_1_svc(RCadr , struct svc_req *);
#define dscudaMemcpyH2HId 702
extern  dscudaMemcpyH2HResult * dscudamemcpyh2hid_1(RCadr , RCbuf , RCsize , CLIENT *);
extern  dscudaMemcpyH2HResult * dscudamemcpyh2hid_1_svc(RCadr , RCbuf , RCsize , struct svc_req *);
#define dscudaMemcpyH2DId 703
extern  dscudaResult * dscudamemcpyh2did_1(RCadr , RCbuf , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpyh2did_1_svc(RCadr , RCbuf , RCsize , struct svc_req *);
#define dscudaMemcpyD2HId 704
extern  dscudaMemcpyD2HResult * dscudamemcpyd2hid_1(RCadr , RCsize , CLIENT *);
extern  dscudaMemcpyD2HResult * dscudamemcpyd2hid_1_svc(RCadr , RCsize , struct svc_req *);
#define dscudaMemcpyD2DId 705
extern  dscudaResult * dscudamemcpyd2did_1(RCadr , RCadr , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpyd2did_1_svc(RCadr , RCadr , RCsize , struct svc_req *);
#define dscudaMemcpyAsyncH2HId 706
extern  dscudaMemcpyAsyncH2HResult * dscudamemcpyasynch2hid_1(RCadr , RCbuf , RCsize , RCstream , CLIENT *);
extern  dscudaMemcpyAsyncH2HResult * dscudamemcpyasynch2hid_1_svc(RCadr , RCbuf , RCsize , RCstream , struct svc_req *);
#define dscudaMemcpyAsyncH2DId 707
extern  dscudaResult * dscudamemcpyasynch2did_1(RCadr , RCbuf , RCsize , RCstream , CLIENT *);
extern  dscudaResult * dscudamemcpyasynch2did_1_svc(RCadr , RCbuf , RCsize , RCstream , struct svc_req *);
#define dscudaMemcpyAsyncD2HId 708
extern  dscudaMemcpyAsyncD2HResult * dscudamemcpyasyncd2hid_1(RCadr , RCsize , RCstream , CLIENT *);
extern  dscudaMemcpyAsyncD2HResult * dscudamemcpyasyncd2hid_1_svc(RCadr , RCsize , RCstream , struct svc_req *);
#define dscudaMemcpyAsyncD2DId 709
extern  dscudaResult * dscudamemcpyasyncd2did_1(RCadr , RCadr , RCsize , RCstream , CLIENT *);
extern  dscudaResult * dscudamemcpyasyncd2did_1_svc(RCadr , RCadr , RCsize , RCstream , struct svc_req *);
#define dscudaMemcpyToSymbolH2DId 710
extern  dscudaResult * dscudamemcpytosymbolh2did_1(int , char *, RCbuf , RCsize , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpytosymbolh2did_1_svc(int , char *, RCbuf , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpyToSymbolD2DId 711
extern  dscudaResult * dscudamemcpytosymbold2did_1(int , char *, RCadr , RCsize , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpytosymbold2did_1_svc(int , char *, RCadr , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpyFromSymbolD2HId 712
extern  dscudaMemcpyFromSymbolD2HResult * dscudamemcpyfromsymbold2hid_1(int , char *, RCsize , RCsize , CLIENT *);
extern  dscudaMemcpyFromSymbolD2HResult * dscudamemcpyfromsymbold2hid_1_svc(int , char *, RCsize , RCsize , struct svc_req *);
#define dscudaMemcpyFromSymbolD2DId 713
extern  dscudaResult * dscudamemcpyfromsymbold2did_1(int , RCadr , char *, RCsize , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpyfromsymbold2did_1_svc(int , RCadr , char *, RCsize , RCsize , struct svc_req *);
#define dscudaMemsetId 714
extern  dscudaResult * dscudamemsetid_1(RCadr , int , RCsize , CLIENT *);
extern  dscudaResult * dscudamemsetid_1_svc(RCadr , int , RCsize , struct svc_req *);
#define dscudaHostAllocId 715
extern  dscudaHostAllocResult * dscudahostallocid_1(RCsize , u_int , CLIENT *);
extern  dscudaHostAllocResult * dscudahostallocid_1_svc(RCsize , u_int , struct svc_req *);
#define dscudaMallocHostId 716
extern  dscudaMallocHostResult * dscudamallochostid_1(RCsize , CLIENT *);
extern  dscudaMallocHostResult * dscudamallochostid_1_svc(RCsize , struct svc_req *);
#define dscudaFreeHostId 717
extern  dscudaResult * dscudafreehostid_1(RCadr , CLIENT *);
extern  dscudaResult * dscudafreehostid_1_svc(RCadr , struct svc_req *);
#define dscudaHostGetDevicePointerId 718
extern  dscudaHostGetDevicePointerResult * dscudahostgetdevicepointerid_1(RCadr , u_int , CLIENT *);
extern  dscudaHostGetDevicePointerResult * dscudahostgetdevicepointerid_1_svc(RCadr , u_int , struct svc_req *);
#define dscudaHostGetFlagsID 719
extern  dscudaHostGetFlagsResult * dscudahostgetflagsid_1(RCadr , CLIENT *);
extern  dscudaHostGetFlagsResult * dscudahostgetflagsid_1_svc(RCadr , struct svc_req *);
#define dscudaMallocArrayId 720
extern  dscudaMallocArrayResult * dscudamallocarrayid_1(RCchanneldesc , RCsize , RCsize , u_int , CLIENT *);
extern  dscudaMallocArrayResult * dscudamallocarrayid_1_svc(RCchanneldesc , RCsize , RCsize , u_int , struct svc_req *);
#define dscudaFreeArrayId 721
extern  dscudaResult * dscudafreearrayid_1(RCadr , CLIENT *);
extern  dscudaResult * dscudafreearrayid_1_svc(RCadr , struct svc_req *);
#define dscudaMemcpyToArrayH2HId 722
extern  dscudaMemcpyToArrayH2HResult * dscudamemcpytoarrayh2hid_1(RCadr , RCsize , RCsize , RCbuf , RCsize , CLIENT *);
extern  dscudaMemcpyToArrayH2HResult * dscudamemcpytoarrayh2hid_1_svc(RCadr , RCsize , RCsize , RCbuf , RCsize , struct svc_req *);
#define dscudaMemcpyToArrayH2DId 723
extern  dscudaResult * dscudamemcpytoarrayh2did_1(RCadr , RCsize , RCsize , RCbuf , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpytoarrayh2did_1_svc(RCadr , RCsize , RCsize , RCbuf , RCsize , struct svc_req *);
#define dscudaMemcpyToArrayD2HId 724
extern  dscudaMemcpyToArrayD2HResult * dscudamemcpytoarrayd2hid_1(RCsize , RCsize , RCadr , RCsize , CLIENT *);
extern  dscudaMemcpyToArrayD2HResult * dscudamemcpytoarrayd2hid_1_svc(RCsize , RCsize , RCadr , RCsize , struct svc_req *);
#define dscudaMemcpyToArrayD2DId 725
extern  dscudaResult * dscudamemcpytoarrayd2did_1(RCadr , RCsize , RCsize , RCadr , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpytoarrayd2did_1_svc(RCadr , RCsize , RCsize , RCadr , RCsize , struct svc_req *);
#define dscudaMallocPitchId 726
extern  dscudaMallocPitchResult * dscudamallocpitchid_1(RCsize , RCsize , CLIENT *);
extern  dscudaMallocPitchResult * dscudamallocpitchid_1_svc(RCsize , RCsize , struct svc_req *);
#define dscudaMemcpy2DToArrayH2HId 727
extern  dscudaMemcpy2DToArrayH2HResult * dscudamemcpy2dtoarrayh2hid_1(RCadr , RCsize , RCsize , RCbuf , RCsize , RCsize , RCsize , CLIENT *);
extern  dscudaMemcpy2DToArrayH2HResult * dscudamemcpy2dtoarrayh2hid_1_svc(RCadr , RCsize , RCsize , RCbuf , RCsize , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpy2DToArrayH2DId 728
extern  dscudaResult * dscudamemcpy2dtoarrayh2did_1(RCadr , RCsize , RCsize , RCbuf , RCsize , RCsize , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpy2dtoarrayh2did_1_svc(RCadr , RCsize , RCsize , RCbuf , RCsize , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpy2DToArrayD2HId 729
extern  dscudaMemcpy2DToArrayD2HResult * dscudamemcpy2dtoarrayd2hid_1(RCsize , RCsize , RCadr , RCsize , RCsize , RCsize , CLIENT *);
extern  dscudaMemcpy2DToArrayD2HResult * dscudamemcpy2dtoarrayd2hid_1_svc(RCsize , RCsize , RCadr , RCsize , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpy2DToArrayD2DId 730
extern  dscudaResult * dscudamemcpy2dtoarrayd2did_1(RCadr , RCsize , RCsize , RCadr , RCsize , RCsize , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpy2dtoarrayd2did_1_svc(RCadr , RCsize , RCsize , RCadr , RCsize , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpy2DH2HId 731
extern  dscudaMemcpy2DH2HResult * dscudamemcpy2dh2hid_1(RCadr , RCsize , RCbuf , RCsize , RCsize , RCsize , CLIENT *);
extern  dscudaMemcpy2DH2HResult * dscudamemcpy2dh2hid_1_svc(RCadr , RCsize , RCbuf , RCsize , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpy2DH2DId 732
extern  dscudaResult * dscudamemcpy2dh2did_1(RCadr , RCsize , RCbuf , RCsize , RCsize , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpy2dh2did_1_svc(RCadr , RCsize , RCbuf , RCsize , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpy2DD2HId 733
extern  dscudaMemcpy2DD2HResult * dscudamemcpy2dd2hid_1(RCsize , RCadr , RCsize , RCsize , RCsize , CLIENT *);
extern  dscudaMemcpy2DD2HResult * dscudamemcpy2dd2hid_1_svc(RCsize , RCadr , RCsize , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpy2DD2DId 734
extern  dscudaResult * dscudamemcpy2dd2did_1(RCadr , RCsize , RCadr , RCsize , RCsize , RCsize , CLIENT *);
extern  dscudaResult * dscudamemcpy2dd2did_1_svc(RCadr , RCsize , RCadr , RCsize , RCsize , RCsize , struct svc_req *);
#define dscudaMemset2DId 735
extern  dscudaResult * dscudamemset2did_1(RCadr , RCsize , int , RCsize , RCsize , CLIENT *);
extern  dscudaResult * dscudamemset2did_1_svc(RCadr , RCsize , int , RCsize , RCsize , struct svc_req *);
#define dscudaMemcpyToSymbolAsyncH2DId 736
extern  dscudaResult * dscudamemcpytosymbolasynch2did_1(int , char *, RCbuf , RCsize , RCsize , RCstream , CLIENT *);
extern  dscudaResult * dscudamemcpytosymbolasynch2did_1_svc(int , char *, RCbuf , RCsize , RCsize , RCstream , struct svc_req *);
#define dscudaMemcpyToSymbolAsyncD2DId 737
extern  dscudaResult * dscudamemcpytosymbolasyncd2did_1(int , char *, RCadr , RCsize , RCsize , RCstream , CLIENT *);
extern  dscudaResult * dscudamemcpytosymbolasyncd2did_1_svc(int , char *, RCadr , RCsize , RCsize , RCstream , struct svc_req *);
#define dscudaMemcpyFromSymbolAsyncD2HId 738
extern  dscudaMemcpyFromSymbolAsyncD2HResult * dscudamemcpyfromsymbolasyncd2hid_1(int , char *, RCsize , RCsize , RCstream , CLIENT *);
extern  dscudaMemcpyFromSymbolAsyncD2HResult * dscudamemcpyfromsymbolasyncd2hid_1_svc(int , char *, RCsize , RCsize , RCstream , struct svc_req *);
#define dscudaMemcpyFromSymbolAsyncD2DId 739
extern  dscudaResult * dscudamemcpyfromsymbolasyncd2did_1(int , RCadr , char *, RCsize , RCsize , RCstream , CLIENT *);
extern  dscudaResult * dscudamemcpyfromsymbolasyncd2did_1_svc(int , RCadr , char *, RCsize , RCsize , RCstream , struct svc_req *);
#define dscudaCreateChannelDescId 1400
extern  dscudaCreateChannelDescResult * dscudacreatechanneldescid_1(int , int , int , int , RCchannelformat , CLIENT *);
extern  dscudaCreateChannelDescResult * dscudacreatechanneldescid_1_svc(int , int , int , int , RCchannelformat , struct svc_req *);
#define dscudaGetChannelDescId 1401
extern  dscudaGetChannelDescResult * dscudagetchanneldescid_1(RCadr , CLIENT *);
extern  dscudaGetChannelDescResult * dscudagetchanneldescid_1_svc(RCadr , struct svc_req *);
#define dscudaBindTextureId 1402
extern  dscudaBindTextureResult * dscudabindtextureid_1(int , char *, RCadr , RCsize , RCtexture , CLIENT *);
extern  dscudaBindTextureResult * dscudabindtextureid_1_svc(int , char *, RCadr , RCsize , RCtexture , struct svc_req *);
#define dscudaBindTexture2DId 1403
extern  dscudaBindTexture2DResult * dscudabindtexture2did_1(int , char *, RCadr , RCsize , RCsize , RCsize , RCtexture , CLIENT *);
extern  dscudaBindTexture2DResult * dscudabindtexture2did_1_svc(int , char *, RCadr , RCsize , RCsize , RCsize , RCtexture , struct svc_req *);
#define dscudaBindTextureToArrayId 1404
extern  dscudaResult * dscudabindtexturetoarrayid_1(int , char *, RCadr , RCtexture , CLIENT *);
extern  dscudaResult * dscudabindtexturetoarrayid_1_svc(int , char *, RCadr , RCtexture , struct svc_req *);
#define dscudaUnbindTextureId 1405
extern  dscudaResult * dscudaunbindtextureid_1(RCtexture , CLIENT *);
extern  dscudaResult * dscudaunbindtextureid_1_svc(RCtexture , struct svc_req *);
#define dscufftPlan3dId 2002
extern  dscufftPlanResult * dscufftplan3did_1(int , int , int , u_int , CLIENT *);
extern  dscufftPlanResult * dscufftplan3did_1_svc(int , int , int , u_int , struct svc_req *);
#define dscufftDestroyId 2004
extern  dscufftResult * dscufftdestroyid_1(u_int , CLIENT *);
extern  dscufftResult * dscufftdestroyid_1_svc(u_int , struct svc_req *);
#define dscufftExecC2CId 2005
extern  dscufftResult * dscufftexecc2cid_1(u_int , RCadr , RCadr , int , CLIENT *);
extern  dscufftResult * dscufftexecc2cid_1_svc(u_int , RCadr , RCadr , int , struct svc_req *);
extern int dscuda_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define dscudaThreadExitId 100
extern  dscudaResult * dscudathreadexitid_1();
extern  dscudaResult * dscudathreadexitid_1_svc();
#define dscudaThreadSynchronizeId 101
extern  dscudaResult * dscudathreadsynchronizeid_1();
extern  dscudaResult * dscudathreadsynchronizeid_1_svc();
#define dscudaThreadSetLimitId 102
extern  dscudaResult * dscudathreadsetlimitid_1();
extern  dscudaResult * dscudathreadsetlimitid_1_svc();
#define dscudaThreadGetLimitId 103
extern  dscudaThreadGetLimitResult * dscudathreadgetlimitid_1();
extern  dscudaThreadGetLimitResult * dscudathreadgetlimitid_1_svc();
#define dscudaThreadSetCacheConfigId 104
extern  dscudaResult * dscudathreadsetcacheconfigid_1();
extern  dscudaResult * dscudathreadsetcacheconfigid_1_svc();
#define dscudaThreadGetCacheConfigId 105
extern  dscudaThreadGetCacheConfigResult * dscudathreadgetcacheconfigid_1();
extern  dscudaThreadGetCacheConfigResult * dscudathreadgetcacheconfigid_1_svc();
#define dscudaGetLastErrorId 200
extern  dscudaResult * dscudagetlasterrorid_1();
extern  dscudaResult * dscudagetlasterrorid_1_svc();
#define dscudaPeekAtLastErrorId 201
extern  dscudaResult * dscudapeekatlasterrorid_1();
extern  dscudaResult * dscudapeekatlasterrorid_1_svc();
#define dscudaGetErrorStringId 202
extern  dscudaGetErrorStringResult * dscudageterrorstringid_1();
extern  dscudaGetErrorStringResult * dscudageterrorstringid_1_svc();
#define dscudaGetDeviceId 300
extern  dscudaGetDeviceResult * dscudagetdeviceid_1();
extern  dscudaGetDeviceResult * dscudagetdeviceid_1_svc();
#define dscudaGetDeviceCountId 301
extern  dscudaGetDeviceCountResult * dscudagetdevicecountid_1();
extern  dscudaGetDeviceCountResult * dscudagetdevicecountid_1_svc();
#define dscudaGetDevicePropertiesId 302
extern  dscudaGetDevicePropertiesResult * dscudagetdevicepropertiesid_1();
extern  dscudaGetDevicePropertiesResult * dscudagetdevicepropertiesid_1_svc();
#define dscudaDriverGetVersionId 303
extern  dscudaDriverGetVersionResult * dscudadrivergetversionid_1();
extern  dscudaDriverGetVersionResult * dscudadrivergetversionid_1_svc();
#define dscudaRuntimeGetVersionId 304
extern  dscudaRuntimeGetVersionResult * dscudaruntimegetversionid_1();
extern  dscudaRuntimeGetVersionResult * dscudaruntimegetversionid_1_svc();
#define dscudaSetDeviceId 305
extern  dscudaResult * dscudasetdeviceid_1();
extern  dscudaResult * dscudasetdeviceid_1_svc();
#define dscudaSetDeviceFlagsId 306
extern  dscudaResult * dscudasetdeviceflagsid_1();
extern  dscudaResult * dscudasetdeviceflagsid_1_svc();
#define dscudaChooseDeviceId 307
extern  dscudaChooseDeviceResult * dscudachoosedeviceid_1();
extern  dscudaChooseDeviceResult * dscudachoosedeviceid_1_svc();
#define dscudaDeviceSynchronize 308
extern  dscudaResult * dscudadevicesynchronize_1();
extern  dscudaResult * dscudadevicesynchronize_1_svc();
#define dscudaDeviceReset 309
extern  dscudaResult * dscudadevicereset_1();
extern  dscudaResult * dscudadevicereset_1_svc();
#define dscudaStreamCreateId 400
extern  dscudaStreamCreateResult * dscudastreamcreateid_1();
extern  dscudaStreamCreateResult * dscudastreamcreateid_1_svc();
#define dscudaStreamDestroyId 401
extern  dscudaResult * dscudastreamdestroyid_1();
extern  dscudaResult * dscudastreamdestroyid_1_svc();
#define dscudaStreamSynchronizeId 402
extern  dscudaResult * dscudastreamsynchronizeid_1();
extern  dscudaResult * dscudastreamsynchronizeid_1_svc();
#define dscudaStreamQueryId 403
extern  dscudaResult * dscudastreamqueryid_1();
extern  dscudaResult * dscudastreamqueryid_1_svc();
#define dscudaStreamWaitEventId 404
extern  dscudaResult * dscudastreamwaiteventid_1();
extern  dscudaResult * dscudastreamwaiteventid_1_svc();
#define dscudaEventCreateId 500
extern  dscudaEventCreateResult * dscudaeventcreateid_1();
extern  dscudaEventCreateResult * dscudaeventcreateid_1_svc();
#define dscudaEventCreateWithFlagsId 501
extern  dscudaEventCreateResult * dscudaeventcreatewithflagsid_1();
extern  dscudaEventCreateResult * dscudaeventcreatewithflagsid_1_svc();
#define dscudaEventDestroyId 502
extern  dscudaResult * dscudaeventdestroyid_1();
extern  dscudaResult * dscudaeventdestroyid_1_svc();
#define dscudaEventElapsedTimeId 503
extern  dscudaEventElapsedTimeResult * dscudaeventelapsedtimeid_1();
extern  dscudaEventElapsedTimeResult * dscudaeventelapsedtimeid_1_svc();
#define dscudaEventRecordId 504
extern  dscudaResult * dscudaeventrecordid_1();
extern  dscudaResult * dscudaeventrecordid_1_svc();
#define dscudaEventSynchronizeId 505
extern  dscudaResult * dscudaeventsynchronizeid_1();
extern  dscudaResult * dscudaeventsynchronizeid_1_svc();
#define dscudaEventQueryId 506
extern  dscudaResult * dscudaeventqueryid_1();
extern  dscudaResult * dscudaeventqueryid_1_svc();
#define dscudaLaunchKernelId 600
extern  void * dscudalaunchkernelid_1();
extern  void * dscudalaunchkernelid_1_svc();
#define dscudaLoadModuleId 601
extern  dscudaLoadModuleResult * dscudaloadmoduleid_1();
extern  dscudaLoadModuleResult * dscudaloadmoduleid_1_svc();
#define dscudaFuncGetAttributesId 602
extern  dscudaFuncGetAttributesResult * dscudafuncgetattributesid_1();
extern  dscudaFuncGetAttributesResult * dscudafuncgetattributesid_1_svc();
#define dscudaMallocId 700
extern  dscudaMallocResult * dscudamallocid_1();
extern  dscudaMallocResult * dscudamallocid_1_svc();
#define dscudaFreeId 701
extern  dscudaResult * dscudafreeid_1();
extern  dscudaResult * dscudafreeid_1_svc();
#define dscudaMemcpyH2HId 702
extern  dscudaMemcpyH2HResult * dscudamemcpyh2hid_1();
extern  dscudaMemcpyH2HResult * dscudamemcpyh2hid_1_svc();
#define dscudaMemcpyH2DId 703
extern  dscudaResult * dscudamemcpyh2did_1();
extern  dscudaResult * dscudamemcpyh2did_1_svc();
#define dscudaMemcpyD2HId 704
extern  dscudaMemcpyD2HResult * dscudamemcpyd2hid_1();
extern  dscudaMemcpyD2HResult * dscudamemcpyd2hid_1_svc();
#define dscudaMemcpyD2DId 705
extern  dscudaResult * dscudamemcpyd2did_1();
extern  dscudaResult * dscudamemcpyd2did_1_svc();
#define dscudaMemcpyAsyncH2HId 706
extern  dscudaMemcpyAsyncH2HResult * dscudamemcpyasynch2hid_1();
extern  dscudaMemcpyAsyncH2HResult * dscudamemcpyasynch2hid_1_svc();
#define dscudaMemcpyAsyncH2DId 707
extern  dscudaResult * dscudamemcpyasynch2did_1();
extern  dscudaResult * dscudamemcpyasynch2did_1_svc();
#define dscudaMemcpyAsyncD2HId 708
extern  dscudaMemcpyAsyncD2HResult * dscudamemcpyasyncd2hid_1();
extern  dscudaMemcpyAsyncD2HResult * dscudamemcpyasyncd2hid_1_svc();
#define dscudaMemcpyAsyncD2DId 709
extern  dscudaResult * dscudamemcpyasyncd2did_1();
extern  dscudaResult * dscudamemcpyasyncd2did_1_svc();
#define dscudaMemcpyToSymbolH2DId 710
extern  dscudaResult * dscudamemcpytosymbolh2did_1();
extern  dscudaResult * dscudamemcpytosymbolh2did_1_svc();
#define dscudaMemcpyToSymbolD2DId 711
extern  dscudaResult * dscudamemcpytosymbold2did_1();
extern  dscudaResult * dscudamemcpytosymbold2did_1_svc();
#define dscudaMemcpyFromSymbolD2HId 712
extern  dscudaMemcpyFromSymbolD2HResult * dscudamemcpyfromsymbold2hid_1();
extern  dscudaMemcpyFromSymbolD2HResult * dscudamemcpyfromsymbold2hid_1_svc();
#define dscudaMemcpyFromSymbolD2DId 713
extern  dscudaResult * dscudamemcpyfromsymbold2did_1();
extern  dscudaResult * dscudamemcpyfromsymbold2did_1_svc();
#define dscudaMemsetId 714
extern  dscudaResult * dscudamemsetid_1();
extern  dscudaResult * dscudamemsetid_1_svc();
#define dscudaHostAllocId 715
extern  dscudaHostAllocResult * dscudahostallocid_1();
extern  dscudaHostAllocResult * dscudahostallocid_1_svc();
#define dscudaMallocHostId 716
extern  dscudaMallocHostResult * dscudamallochostid_1();
extern  dscudaMallocHostResult * dscudamallochostid_1_svc();
#define dscudaFreeHostId 717
extern  dscudaResult * dscudafreehostid_1();
extern  dscudaResult * dscudafreehostid_1_svc();
#define dscudaHostGetDevicePointerId 718
extern  dscudaHostGetDevicePointerResult * dscudahostgetdevicepointerid_1();
extern  dscudaHostGetDevicePointerResult * dscudahostgetdevicepointerid_1_svc();
#define dscudaHostGetFlagsID 719
extern  dscudaHostGetFlagsResult * dscudahostgetflagsid_1();
extern  dscudaHostGetFlagsResult * dscudahostgetflagsid_1_svc();
#define dscudaMallocArrayId 720
extern  dscudaMallocArrayResult * dscudamallocarrayid_1();
extern  dscudaMallocArrayResult * dscudamallocarrayid_1_svc();
#define dscudaFreeArrayId 721
extern  dscudaResult * dscudafreearrayid_1();
extern  dscudaResult * dscudafreearrayid_1_svc();
#define dscudaMemcpyToArrayH2HId 722
extern  dscudaMemcpyToArrayH2HResult * dscudamemcpytoarrayh2hid_1();
extern  dscudaMemcpyToArrayH2HResult * dscudamemcpytoarrayh2hid_1_svc();
#define dscudaMemcpyToArrayH2DId 723
extern  dscudaResult * dscudamemcpytoarrayh2did_1();
extern  dscudaResult * dscudamemcpytoarrayh2did_1_svc();
#define dscudaMemcpyToArrayD2HId 724
extern  dscudaMemcpyToArrayD2HResult * dscudamemcpytoarrayd2hid_1();
extern  dscudaMemcpyToArrayD2HResult * dscudamemcpytoarrayd2hid_1_svc();
#define dscudaMemcpyToArrayD2DId 725
extern  dscudaResult * dscudamemcpytoarrayd2did_1();
extern  dscudaResult * dscudamemcpytoarrayd2did_1_svc();
#define dscudaMallocPitchId 726
extern  dscudaMallocPitchResult * dscudamallocpitchid_1();
extern  dscudaMallocPitchResult * dscudamallocpitchid_1_svc();
#define dscudaMemcpy2DToArrayH2HId 727
extern  dscudaMemcpy2DToArrayH2HResult * dscudamemcpy2dtoarrayh2hid_1();
extern  dscudaMemcpy2DToArrayH2HResult * dscudamemcpy2dtoarrayh2hid_1_svc();
#define dscudaMemcpy2DToArrayH2DId 728
extern  dscudaResult * dscudamemcpy2dtoarrayh2did_1();
extern  dscudaResult * dscudamemcpy2dtoarrayh2did_1_svc();
#define dscudaMemcpy2DToArrayD2HId 729
extern  dscudaMemcpy2DToArrayD2HResult * dscudamemcpy2dtoarrayd2hid_1();
extern  dscudaMemcpy2DToArrayD2HResult * dscudamemcpy2dtoarrayd2hid_1_svc();
#define dscudaMemcpy2DToArrayD2DId 730
extern  dscudaResult * dscudamemcpy2dtoarrayd2did_1();
extern  dscudaResult * dscudamemcpy2dtoarrayd2did_1_svc();
#define dscudaMemcpy2DH2HId 731
extern  dscudaMemcpy2DH2HResult * dscudamemcpy2dh2hid_1();
extern  dscudaMemcpy2DH2HResult * dscudamemcpy2dh2hid_1_svc();
#define dscudaMemcpy2DH2DId 732
extern  dscudaResult * dscudamemcpy2dh2did_1();
extern  dscudaResult * dscudamemcpy2dh2did_1_svc();
#define dscudaMemcpy2DD2HId 733
extern  dscudaMemcpy2DD2HResult * dscudamemcpy2dd2hid_1();
extern  dscudaMemcpy2DD2HResult * dscudamemcpy2dd2hid_1_svc();
#define dscudaMemcpy2DD2DId 734
extern  dscudaResult * dscudamemcpy2dd2did_1();
extern  dscudaResult * dscudamemcpy2dd2did_1_svc();
#define dscudaMemset2DId 735
extern  dscudaResult * dscudamemset2did_1();
extern  dscudaResult * dscudamemset2did_1_svc();
#define dscudaMemcpyToSymbolAsyncH2DId 736
extern  dscudaResult * dscudamemcpytosymbolasynch2did_1();
extern  dscudaResult * dscudamemcpytosymbolasynch2did_1_svc();
#define dscudaMemcpyToSymbolAsyncD2DId 737
extern  dscudaResult * dscudamemcpytosymbolasyncd2did_1();
extern  dscudaResult * dscudamemcpytosymbolasyncd2did_1_svc();
#define dscudaMemcpyFromSymbolAsyncD2HId 738
extern  dscudaMemcpyFromSymbolAsyncD2HResult * dscudamemcpyfromsymbolasyncd2hid_1();
extern  dscudaMemcpyFromSymbolAsyncD2HResult * dscudamemcpyfromsymbolasyncd2hid_1_svc();
#define dscudaMemcpyFromSymbolAsyncD2DId 739
extern  dscudaResult * dscudamemcpyfromsymbolasyncd2did_1();
extern  dscudaResult * dscudamemcpyfromsymbolasyncd2did_1_svc();
#define dscudaCreateChannelDescId 1400
extern  dscudaCreateChannelDescResult * dscudacreatechanneldescid_1();
extern  dscudaCreateChannelDescResult * dscudacreatechanneldescid_1_svc();
#define dscudaGetChannelDescId 1401
extern  dscudaGetChannelDescResult * dscudagetchanneldescid_1();
extern  dscudaGetChannelDescResult * dscudagetchanneldescid_1_svc();
#define dscudaBindTextureId 1402
extern  dscudaBindTextureResult * dscudabindtextureid_1();
extern  dscudaBindTextureResult * dscudabindtextureid_1_svc();
#define dscudaBindTexture2DId 1403
extern  dscudaBindTexture2DResult * dscudabindtexture2did_1();
extern  dscudaBindTexture2DResult * dscudabindtexture2did_1_svc();
#define dscudaBindTextureToArrayId 1404
extern  dscudaResult * dscudabindtexturetoarrayid_1();
extern  dscudaResult * dscudabindtexturetoarrayid_1_svc();
#define dscudaUnbindTextureId 1405
extern  dscudaResult * dscudaunbindtextureid_1();
extern  dscudaResult * dscudaunbindtextureid_1_svc();
#define dscufftPlan3dId 2002
extern  dscufftPlanResult * dscufftplan3did_1();
extern  dscufftPlanResult * dscufftplan3did_1_svc();
#define dscufftDestroyId 2004
extern  dscufftResult * dscufftdestroyid_1();
extern  dscufftResult * dscufftdestroyid_1_svc();
#define dscufftExecC2CId 2005
extern  dscufftResult * dscufftexecc2cid_1();
extern  dscufftResult * dscufftexecc2cid_1_svc();
extern int dscuda_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_RCadr (XDR *, RCadr*);
extern  bool_t xdr_RCstream (XDR *, RCstream*);
extern  bool_t xdr_RCevent (XDR *, RCevent*);
extern  bool_t xdr_RCipaddr (XDR *, RCipaddr*);
extern  bool_t xdr_RCsize (XDR *, RCsize*);
extern  bool_t xdr_RCerror (XDR *, RCerror*);
extern  bool_t xdr_RCbuf (XDR *, RCbuf*);
extern  bool_t xdr_RCchannelformat (XDR *, RCchannelformat*);
extern  bool_t xdr_RCpid (XDR *, RCpid*);
extern  bool_t xdr_RCchanneldesc_t (XDR *, RCchanneldesc_t*);
extern  bool_t xdr_RCchanneldesc (XDR *, RCchanneldesc*);
extern  bool_t xdr_RCtexture_t (XDR *, RCtexture_t*);
extern  bool_t xdr_RCtexture (XDR *, RCtexture*);
extern  bool_t xdr_RCfuncattr_t (XDR *, RCfuncattr_t*);
extern  bool_t xdr_RCfuncattr (XDR *, RCfuncattr*);
extern  bool_t xdr_RCargType (XDR *, RCargType*);
extern  bool_t xdr_RCargVal (XDR *, RCargVal*);
extern  bool_t xdr_RCarg (XDR *, RCarg*);
extern  bool_t xdr_RCargs (XDR *, RCargs*);
extern  bool_t xdr_dscudaResult (XDR *, dscudaResult*);
extern  bool_t xdr_dscudaThreadGetLimitResult (XDR *, dscudaThreadGetLimitResult*);
extern  bool_t xdr_dscudaThreadGetCacheConfigResult (XDR *, dscudaThreadGetCacheConfigResult*);
extern  bool_t xdr_dscudaMallocResult (XDR *, dscudaMallocResult*);
extern  bool_t xdr_dscudaHostAllocResult (XDR *, dscudaHostAllocResult*);
extern  bool_t xdr_dscudaMallocHostResult (XDR *, dscudaMallocHostResult*);
extern  bool_t xdr_dscudaMallocArrayResult (XDR *, dscudaMallocArrayResult*);
extern  bool_t xdr_dscudaMallocPitchResult (XDR *, dscudaMallocPitchResult*);
extern  bool_t xdr_dscudaMemcpyD2HResult (XDR *, dscudaMemcpyD2HResult*);
extern  bool_t xdr_dscudaMemcpyH2HResult (XDR *, dscudaMemcpyH2HResult*);
extern  bool_t xdr_dscudaMemcpyToArrayD2HResult (XDR *, dscudaMemcpyToArrayD2HResult*);
extern  bool_t xdr_dscudaMemcpyToArrayH2HResult (XDR *, dscudaMemcpyToArrayH2HResult*);
extern  bool_t xdr_dscudaMemcpy2DToArrayD2HResult (XDR *, dscudaMemcpy2DToArrayD2HResult*);
extern  bool_t xdr_dscudaMemcpy2DToArrayH2HResult (XDR *, dscudaMemcpy2DToArrayH2HResult*);
extern  bool_t xdr_dscudaMemcpy2DD2HResult (XDR *, dscudaMemcpy2DD2HResult*);
extern  bool_t xdr_dscudaMemcpy2DH2HResult (XDR *, dscudaMemcpy2DH2HResult*);
extern  bool_t xdr_dscudaGetDeviceResult (XDR *, dscudaGetDeviceResult*);
extern  bool_t xdr_dscudaGetDeviceCountResult (XDR *, dscudaGetDeviceCountResult*);
extern  bool_t xdr_dscudaGetDevicePropertiesResult (XDR *, dscudaGetDevicePropertiesResult*);
extern  bool_t xdr_dscudaDriverGetVersionResult (XDR *, dscudaDriverGetVersionResult*);
extern  bool_t xdr_dscudaRuntimeGetVersionResult (XDR *, dscudaRuntimeGetVersionResult*);
extern  bool_t xdr_dscudaGetErrorStringResult (XDR *, dscudaGetErrorStringResult*);
extern  bool_t xdr_dscudaCreateChannelDescResult (XDR *, dscudaCreateChannelDescResult*);
extern  bool_t xdr_dscudaGetChannelDescResult (XDR *, dscudaGetChannelDescResult*);
extern  bool_t xdr_dscudaChooseDeviceResult (XDR *, dscudaChooseDeviceResult*);
extern  bool_t xdr_dscudaMemcpyAsyncD2HResult (XDR *, dscudaMemcpyAsyncD2HResult*);
extern  bool_t xdr_dscudaMemcpyAsyncH2HResult (XDR *, dscudaMemcpyAsyncH2HResult*);
extern  bool_t xdr_dscudaMemcpyFromSymbolD2HResult (XDR *, dscudaMemcpyFromSymbolD2HResult*);
extern  bool_t xdr_dscudaMemcpyFromSymbolAsyncD2HResult (XDR *, dscudaMemcpyFromSymbolAsyncD2HResult*);
extern  bool_t xdr_dscudaStreamCreateResult (XDR *, dscudaStreamCreateResult*);
extern  bool_t xdr_dscudaEventCreateResult (XDR *, dscudaEventCreateResult*);
extern  bool_t xdr_dscudaEventElapsedTimeResult (XDR *, dscudaEventElapsedTimeResult*);
extern  bool_t xdr_dscudaHostGetDevicePointerResult (XDR *, dscudaHostGetDevicePointerResult*);
extern  bool_t xdr_dscudaHostGetFlagsResult (XDR *, dscudaHostGetFlagsResult*);
extern  bool_t xdr_dscudaLoadModuleResult (XDR *, dscudaLoadModuleResult*);
extern  bool_t xdr_dscudaFuncGetAttributesResult (XDR *, dscudaFuncGetAttributesResult*);
extern  bool_t xdr_dscudaBindTextureResult (XDR *, dscudaBindTextureResult*);
extern  bool_t xdr_dscudaBindTexture2DResult (XDR *, dscudaBindTexture2DResult*);
extern  bool_t xdr_dscufftResult (XDR *, dscufftResult*);
extern  bool_t xdr_dscufftPlanResult (XDR *, dscufftPlanResult*);
extern  bool_t xdr_dscublasResult (XDR *, dscublasResult*);
extern  bool_t xdr_dscublasCreateResult (XDR *, dscublasCreateResult*);
extern  bool_t xdr_dscublasGetVectorResult (XDR *, dscublasGetVectorResult*);
extern  bool_t xdr_RCdim3 (XDR *, RCdim3*);
extern  bool_t xdr_dscudathreadsetlimitid_1_argument (XDR *, dscudathreadsetlimitid_1_argument*);
extern  bool_t xdr_dscudastreamwaiteventid_1_argument (XDR *, dscudastreamwaiteventid_1_argument*);
extern  bool_t xdr_dscudaeventelapsedtimeid_1_argument (XDR *, dscudaeventelapsedtimeid_1_argument*);
extern  bool_t xdr_dscudaeventrecordid_1_argument (XDR *, dscudaeventrecordid_1_argument*);
extern  bool_t xdr_dscudalaunchkernelid_1_argument (XDR *, dscudalaunchkernelid_1_argument*);
extern  bool_t xdr_dscudaloadmoduleid_1_argument (XDR *, dscudaloadmoduleid_1_argument*);
extern  bool_t xdr_dscudafuncgetattributesid_1_argument (XDR *, dscudafuncgetattributesid_1_argument*);
extern  bool_t xdr_dscudamemcpyh2hid_1_argument (XDR *, dscudamemcpyh2hid_1_argument*);
extern  bool_t xdr_dscudamemcpyh2did_1_argument (XDR *, dscudamemcpyh2did_1_argument*);
extern  bool_t xdr_dscudamemcpyd2hid_1_argument (XDR *, dscudamemcpyd2hid_1_argument*);
extern  bool_t xdr_dscudamemcpyd2did_1_argument (XDR *, dscudamemcpyd2did_1_argument*);
extern  bool_t xdr_dscudamemcpyasynch2hid_1_argument (XDR *, dscudamemcpyasynch2hid_1_argument*);
extern  bool_t xdr_dscudamemcpyasynch2did_1_argument (XDR *, dscudamemcpyasynch2did_1_argument*);
extern  bool_t xdr_dscudamemcpyasyncd2hid_1_argument (XDR *, dscudamemcpyasyncd2hid_1_argument*);
extern  bool_t xdr_dscudamemcpyasyncd2did_1_argument (XDR *, dscudamemcpyasyncd2did_1_argument*);
extern  bool_t xdr_dscudamemcpytosymbolh2did_1_argument (XDR *, dscudamemcpytosymbolh2did_1_argument*);
extern  bool_t xdr_dscudamemcpytosymbold2did_1_argument (XDR *, dscudamemcpytosymbold2did_1_argument*);
extern  bool_t xdr_dscudamemcpyfromsymbold2hid_1_argument (XDR *, dscudamemcpyfromsymbold2hid_1_argument*);
extern  bool_t xdr_dscudamemcpyfromsymbold2did_1_argument (XDR *, dscudamemcpyfromsymbold2did_1_argument*);
extern  bool_t xdr_dscudamemsetid_1_argument (XDR *, dscudamemsetid_1_argument*);
extern  bool_t xdr_dscudahostallocid_1_argument (XDR *, dscudahostallocid_1_argument*);
extern  bool_t xdr_dscudahostgetdevicepointerid_1_argument (XDR *, dscudahostgetdevicepointerid_1_argument*);
extern  bool_t xdr_dscudamallocarrayid_1_argument (XDR *, dscudamallocarrayid_1_argument*);
extern  bool_t xdr_dscudamemcpytoarrayh2hid_1_argument (XDR *, dscudamemcpytoarrayh2hid_1_argument*);
extern  bool_t xdr_dscudamemcpytoarrayh2did_1_argument (XDR *, dscudamemcpytoarrayh2did_1_argument*);
extern  bool_t xdr_dscudamemcpytoarrayd2hid_1_argument (XDR *, dscudamemcpytoarrayd2hid_1_argument*);
extern  bool_t xdr_dscudamemcpytoarrayd2did_1_argument (XDR *, dscudamemcpytoarrayd2did_1_argument*);
extern  bool_t xdr_dscudamallocpitchid_1_argument (XDR *, dscudamallocpitchid_1_argument*);
extern  bool_t xdr_dscudamemcpy2dtoarrayh2hid_1_argument (XDR *, dscudamemcpy2dtoarrayh2hid_1_argument*);
extern  bool_t xdr_dscudamemcpy2dtoarrayh2did_1_argument (XDR *, dscudamemcpy2dtoarrayh2did_1_argument*);
extern  bool_t xdr_dscudamemcpy2dtoarrayd2hid_1_argument (XDR *, dscudamemcpy2dtoarrayd2hid_1_argument*);
extern  bool_t xdr_dscudamemcpy2dtoarrayd2did_1_argument (XDR *, dscudamemcpy2dtoarrayd2did_1_argument*);
extern  bool_t xdr_dscudamemcpy2dh2hid_1_argument (XDR *, dscudamemcpy2dh2hid_1_argument*);
extern  bool_t xdr_dscudamemcpy2dh2did_1_argument (XDR *, dscudamemcpy2dh2did_1_argument*);
extern  bool_t xdr_dscudamemcpy2dd2hid_1_argument (XDR *, dscudamemcpy2dd2hid_1_argument*);
extern  bool_t xdr_dscudamemcpy2dd2did_1_argument (XDR *, dscudamemcpy2dd2did_1_argument*);
extern  bool_t xdr_dscudamemset2did_1_argument (XDR *, dscudamemset2did_1_argument*);
extern  bool_t xdr_dscudamemcpytosymbolasynch2did_1_argument (XDR *, dscudamemcpytosymbolasynch2did_1_argument*);
extern  bool_t xdr_dscudamemcpytosymbolasyncd2did_1_argument (XDR *, dscudamemcpytosymbolasyncd2did_1_argument*);
extern  bool_t xdr_dscudamemcpyfromsymbolasyncd2hid_1_argument (XDR *, dscudamemcpyfromsymbolasyncd2hid_1_argument*);
extern  bool_t xdr_dscudamemcpyfromsymbolasyncd2did_1_argument (XDR *, dscudamemcpyfromsymbolasyncd2did_1_argument*);
extern  bool_t xdr_dscudacreatechanneldescid_1_argument (XDR *, dscudacreatechanneldescid_1_argument*);
extern  bool_t xdr_dscudabindtextureid_1_argument (XDR *, dscudabindtextureid_1_argument*);
extern  bool_t xdr_dscudabindtexture2did_1_argument (XDR *, dscudabindtexture2did_1_argument*);
extern  bool_t xdr_dscudabindtexturetoarrayid_1_argument (XDR *, dscudabindtexturetoarrayid_1_argument*);
extern  bool_t xdr_dscufftplan3did_1_argument (XDR *, dscufftplan3did_1_argument*);
extern  bool_t xdr_dscufftexecc2cid_1_argument (XDR *, dscufftexecc2cid_1_argument*);

#else /* K&R C */
extern bool_t xdr_RCadr ();
extern bool_t xdr_RCstream ();
extern bool_t xdr_RCevent ();
extern bool_t xdr_RCipaddr ();
extern bool_t xdr_RCsize ();
extern bool_t xdr_RCerror ();
extern bool_t xdr_RCbuf ();
extern bool_t xdr_RCchannelformat ();
extern bool_t xdr_RCpid ();
extern bool_t xdr_RCchanneldesc_t ();
extern bool_t xdr_RCchanneldesc ();
extern bool_t xdr_RCtexture_t ();
extern bool_t xdr_RCtexture ();
extern bool_t xdr_RCfuncattr_t ();
extern bool_t xdr_RCfuncattr ();
extern bool_t xdr_RCargType ();
extern bool_t xdr_RCargVal ();
extern bool_t xdr_RCarg ();
extern bool_t xdr_RCargs ();
extern bool_t xdr_dscudaResult ();
extern bool_t xdr_dscudaThreadGetLimitResult ();
extern bool_t xdr_dscudaThreadGetCacheConfigResult ();
extern bool_t xdr_dscudaMallocResult ();
extern bool_t xdr_dscudaHostAllocResult ();
extern bool_t xdr_dscudaMallocHostResult ();
extern bool_t xdr_dscudaMallocArrayResult ();
extern bool_t xdr_dscudaMallocPitchResult ();
extern bool_t xdr_dscudaMemcpyD2HResult ();
extern bool_t xdr_dscudaMemcpyH2HResult ();
extern bool_t xdr_dscudaMemcpyToArrayD2HResult ();
extern bool_t xdr_dscudaMemcpyToArrayH2HResult ();
extern bool_t xdr_dscudaMemcpy2DToArrayD2HResult ();
extern bool_t xdr_dscudaMemcpy2DToArrayH2HResult ();
extern bool_t xdr_dscudaMemcpy2DD2HResult ();
extern bool_t xdr_dscudaMemcpy2DH2HResult ();
extern bool_t xdr_dscudaGetDeviceResult ();
extern bool_t xdr_dscudaGetDeviceCountResult ();
extern bool_t xdr_dscudaGetDevicePropertiesResult ();
extern bool_t xdr_dscudaDriverGetVersionResult ();
extern bool_t xdr_dscudaRuntimeGetVersionResult ();
extern bool_t xdr_dscudaGetErrorStringResult ();
extern bool_t xdr_dscudaCreateChannelDescResult ();
extern bool_t xdr_dscudaGetChannelDescResult ();
extern bool_t xdr_dscudaChooseDeviceResult ();
extern bool_t xdr_dscudaMemcpyAsyncD2HResult ();
extern bool_t xdr_dscudaMemcpyAsyncH2HResult ();
extern bool_t xdr_dscudaMemcpyFromSymbolD2HResult ();
extern bool_t xdr_dscudaMemcpyFromSymbolAsyncD2HResult ();
extern bool_t xdr_dscudaStreamCreateResult ();
extern bool_t xdr_dscudaEventCreateResult ();
extern bool_t xdr_dscudaEventElapsedTimeResult ();
extern bool_t xdr_dscudaHostGetDevicePointerResult ();
extern bool_t xdr_dscudaHostGetFlagsResult ();
extern bool_t xdr_dscudaLoadModuleResult ();
extern bool_t xdr_dscudaFuncGetAttributesResult ();
extern bool_t xdr_dscudaBindTextureResult ();
extern bool_t xdr_dscudaBindTexture2DResult ();
extern bool_t xdr_dscufftResult ();
extern bool_t xdr_dscufftPlanResult ();
extern bool_t xdr_dscublasResult ();
extern bool_t xdr_dscublasCreateResult ();
extern bool_t xdr_dscublasGetVectorResult ();
extern bool_t xdr_RCdim3 ();
extern bool_t xdr_dscudathreadsetlimitid_1_argument ();
extern bool_t xdr_dscudastreamwaiteventid_1_argument ();
extern bool_t xdr_dscudaeventelapsedtimeid_1_argument ();
extern bool_t xdr_dscudaeventrecordid_1_argument ();
extern bool_t xdr_dscudalaunchkernelid_1_argument ();
extern bool_t xdr_dscudaloadmoduleid_1_argument ();
extern bool_t xdr_dscudafuncgetattributesid_1_argument ();
extern bool_t xdr_dscudamemcpyh2hid_1_argument ();
extern bool_t xdr_dscudamemcpyh2did_1_argument ();
extern bool_t xdr_dscudamemcpyd2hid_1_argument ();
extern bool_t xdr_dscudamemcpyd2did_1_argument ();
extern bool_t xdr_dscudamemcpyasynch2hid_1_argument ();
extern bool_t xdr_dscudamemcpyasynch2did_1_argument ();
extern bool_t xdr_dscudamemcpyasyncd2hid_1_argument ();
extern bool_t xdr_dscudamemcpyasyncd2did_1_argument ();
extern bool_t xdr_dscudamemcpytosymbolh2did_1_argument ();
extern bool_t xdr_dscudamemcpytosymbold2did_1_argument ();
extern bool_t xdr_dscudamemcpyfromsymbold2hid_1_argument ();
extern bool_t xdr_dscudamemcpyfromsymbold2did_1_argument ();
extern bool_t xdr_dscudamemsetid_1_argument ();
extern bool_t xdr_dscudahostallocid_1_argument ();
extern bool_t xdr_dscudahostgetdevicepointerid_1_argument ();
extern bool_t xdr_dscudamallocarrayid_1_argument ();
extern bool_t xdr_dscudamemcpytoarrayh2hid_1_argument ();
extern bool_t xdr_dscudamemcpytoarrayh2did_1_argument ();
extern bool_t xdr_dscudamemcpytoarrayd2hid_1_argument ();
extern bool_t xdr_dscudamemcpytoarrayd2did_1_argument ();
extern bool_t xdr_dscudamallocpitchid_1_argument ();
extern bool_t xdr_dscudamemcpy2dtoarrayh2hid_1_argument ();
extern bool_t xdr_dscudamemcpy2dtoarrayh2did_1_argument ();
extern bool_t xdr_dscudamemcpy2dtoarrayd2hid_1_argument ();
extern bool_t xdr_dscudamemcpy2dtoarrayd2did_1_argument ();
extern bool_t xdr_dscudamemcpy2dh2hid_1_argument ();
extern bool_t xdr_dscudamemcpy2dh2did_1_argument ();
extern bool_t xdr_dscudamemcpy2dd2hid_1_argument ();
extern bool_t xdr_dscudamemcpy2dd2did_1_argument ();
extern bool_t xdr_dscudamemset2did_1_argument ();
extern bool_t xdr_dscudamemcpytosymbolasynch2did_1_argument ();
extern bool_t xdr_dscudamemcpytosymbolasyncd2did_1_argument ();
extern bool_t xdr_dscudamemcpyfromsymbolasyncd2hid_1_argument ();
extern bool_t xdr_dscudamemcpyfromsymbolasyncd2did_1_argument ();
extern bool_t xdr_dscudacreatechanneldescid_1_argument ();
extern bool_t xdr_dscudabindtextureid_1_argument ();
extern bool_t xdr_dscudabindtexture2did_1_argument ();
extern bool_t xdr_dscudabindtexturetoarrayid_1_argument ();
extern bool_t xdr_dscufftplan3did_1_argument ();
extern bool_t xdr_dscufftexecc2cid_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DSCUDARPC_H_RPCGEN */
